version: '3.4'
services:
  image_rotate:
    image: dock101/image_rotate:x64
    container_name: prod_image_rotate
    stdin_open: true
    tty: true
    volumes: 
      - persistent_volume:/usr/src/app/build
    network_mode: host

volumes:
  persistent_volume:
    external: true