version: '3.4'
services:
  image_rotate:
    image: dock101/image_rotate:x64
    container_name: prod_image_rotate
    restart: "always"
    stdin_open: true
    tty: true
    volumes: 
      - ./home/ubuntu/actions-runner/_work/NavVis/NavVis/:/usr/src/app/build
    network_mode: host