version: '3.4'
services:
  image_rotate:
    container_name: dev_image_rotate
    image: dock101/image_rotate.dev:x64
    restart: "always"
    volumes:
      - ./:/usr/src/app/build
    network_mode: host