version: '3.4'
services:
  image_rotate:
    image: dock101/image_rotate:arm
    restart: "always"
    stdin_open: true
    tty: true
    volumes: 
      - ./:/usr/src/app/build
    network_mode: host