name: Docker CI / CD

on:
  push:

jobs:
  build_x64:
    name: Prepare base image for x64
    runs-on: self-hosted 
    environment: dockerhub
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: DockerHub login
        run: echo '${{ secrets.DOCKERHUB_PASSWORD }}' | sudo docker login --username dock101 --password-stdin
      - name: Pushing base image to docker hub
        run: sudo chmod 777 ./package.sh && ./package.sh -e
  
  dev_x64:
    name: Prepare development image for x64
    runs-on: self-hosted 
    environment: dockerhub
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: DockerHub login
        run: echo '${{ secrets.DOCKERHUB_PASSWORD }}' | docker login --username dock101 --password-stdin
      - name: Pushing dev image to docker hub
        run: sudo chmod 777 ./package.sh && ./package.sh -b
      - name: Deploying to development Environment
        run: sudo chmod 777 ./package.sh && ./package.sh -dd
        if: ${{ github.ref == 'refs/heads/dev-*' }}
    needs: build_x64

  test_x64:
    name: Prepare test image for x64
    runs-on: self-hosted 
    environment: dockerhub
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: DockerHub login
        run: echo '${{ secrets.DOCKERHUB_PASSWORD }}' | sudo docker login --username dock101 --password-stdin
      - name: Pushing test image to docker hub
        run: sudo chmod 777 ./package.sh && ./package.sh -t
      - name: Deploying to Test Environment
        run: sudo chmod 777 ./package.sh && ./package.sh -dt
        if: ${{ github.ref == 'refs/heads/dev-*' }}
    needs: [build_x64, dev_x64]

  deploy_x64:
    name: Updating Production deployment image for x64
    runs-on: self-hosted 
    environment: dockerhub
    steps:
      - name: Checkout to master branch
        uses: actions/checkout@main
      - name: DockerHub login
        run: echo '${{ secrets.DOCKERHUB_PASSWORD }}' | sudo docker login --username dock101 --password-stdin
      - name: Pushing prod image to docker hub
        run: sudo chmod 777 ./package.sh && ./package.sh -ud
      - name: Deploying into prod environment
        run: sudo chmod 777 ./package.sh && ./package.sh -d
        if: ${{ github.ref == 'refs/heads/main' }}
    needs: [build_x64, dev_x64]
        